### ISSUE TITLE
Further information on usage

### ISSUE THREAD

**Issue by DRussellSTFC** [locationlabs/influxdb-nagios-plugin#7]
Further information required

I am trying to use this plugin to query an influxdb that I have created to record decibels. I can query in influx for what I am looking for using the following code:
`select "Value" from "PT8005".."Test location" where time > now() - 10m`
Where: 
- PT8005 is the database
- Test location is the measurement
- Value is the field

Having used what I think is the correct syntax within the plugin:
`./check_influxdb_query.py --host localhost --port 8086 --schema PT8005 --query="SELECT Value FROM Test location WHERE time > now() - 10m" --warning='0:75' --critical='90'`

&&

`./check_influxdb_query.py --host localhost --port 8086 --schema PT8005 --query "SELECT Value FROM Test location WHERE time > now() - 10m" --warning='0:75' --critical='90'`
 
Output: 

Traceback (most recent call last):
  File "./check_influxdb_query.py", line 131, in <module>
    resultset_list = influx_client.query(args.query)
  File "/usr/local/lib/python3.7/dist-packages/influxdb/client.py", line 527, in query
    expected_response_code=expected_response_code
  File "/usr/local/lib/python3.7/dist-packages/influxdb/client.py", line 378, in request
    raise InfluxDBClientError(err_msg, response.status_code)
influxdb.exceptions.InfluxDBClientError: 400: {"error":"error parsing query: found location, expected ; at line 1, char 24"}

Note I am using Debian OS.

Any pointers will be appreciated.

David

**Comment by DRussellSTFC** [comment]
After a lot of playing I found that having "Test location" as measurement was causing an issue. I made a new measurement named "Sound" this helped locate the query I was trying to run. In addition I noticed that I had missed "mean(Value)" as my intended query field was "Value". This is now working and I have incorporated into Nagios as a service.
